### ISSUE TITLE
Allow other elements, like mehrmaid

### ISSUE THREAD

**Issue by stakaz** [gitcpy/mermaid-zoom-drag#1]
Hello, it would be great, if one could select or provide (through an option) for which elements the panel is generated.

One example is mehrmaid (https://github.com/huterguier/obsidian-mehrmaid) which allows for markdown inside flowcharts.

**Comment by gitcpy** [comment]
Hello， do you mean to select an element or an node , and then to drag or zoom it in the container?

**Comment by stakaz** [comment]
Hello, I think so. For now the plugin searches for all mermaid' in the note, which is hardcoded. It would be great, if one could provide other names of elements as well. This would make the plugin much more universal and in particular it would make it possible to use it together with mehrmaid, which is a great extension of mermaid allowing Zou to use markdown elements within mermaid elements.

Aug 24, 2024 18:23:28 gitcpy ***@***.***>:

**Comment by gitcpy** [comment]
Hello, I developed another plugin. Here is the url : https://github.com/gitcpy/obsidian-mermaid-pop . 
The function is to click the mermaid in the md note, then a popup comes out. 
And then you could drag or zoom it. I think it would be much more better for user.  
Just try it.

**Comment by stakaz** [comment]
Yes, this is a frat plugin, however, it still does not work on mehrmaid diagrams. So, the issue would be the same here: allowing additional 'key names'.

Aug 24, 2024 19:16:11 gitcpy ***@***.***>:

**Comment by gitcpy** [comment]
Maybe I will find sometime to update the plugin for the excellent advice. I don't how long to complete it. Hope not long. Thanks so much.

**Comment by stakaz** [comment]
Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.

**Comment by gitcpy** [comment]
I tested before our co-work.
But I have troubles in pulling files, just forget it, I will try again.
The mermaid-zoom-drag plugin is fine for the html hierachy of 'div with class-mermaid' -&gt; 'svg'.
But in merhmaid, it has a differenty hierachy, 'div with class=block...' -&gt; 'svg',&nbsp;
so the mermaid-zoom-drag plugin is not fine with.
That is why I plan to adapt to different tags or classes...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月15日(星期天) 凌晨3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Allow other elements, like mehrmaid (Issue #1)





 
Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.

**Comment by stakaz** [comment]
Ah, I see. I apprechiate your work. Many thnaks to dive in into this issue :)

**Comment by Ssentiago** [comment]
> Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.

There is no release with this fix yet, please wait for @gitcpy to create one.

But the fix works, here's a video (sorry for the quality):
![2024-09-15 00-19-04](https://github.com/user-attachments/assets/dc99fdc3-3a17-4f28-a834-6f9071cae5e3)

**Comment by gitcpy** [comment]
1. I pull all latest files from github respository, as seen above
2. Execute "tsc"
3. I got 4 files : main.js, main.d.ts, constants.js, constants.d.ts
4. And put 6 files into the doc "G:\ObsidianFile\ObsidianPlugin\.obsidian\plugins\mermaid-zoom-drag"&nbsp;



5. Load in ob, then I got the error





------------------------------


I don't know how to load the plugin if it has more one file.
The key point is I don't know how to use "require" in ob js and wether to put the *.d.ts files to release.


I just want to make a test before releasing,&nbsp; and I had problems about pulling files before for quite a while, finally shooted out.
So I come to the testing part, and encounter the loading problem above.
Could you please give me some tips?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月15日(星期天) 凌晨5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Allow other elements, like mehrmaid (Issue #1)





  
Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.
  
There is no release with this fix yet, please wait for @gitcpy to create one.
 
But the fix works, here's a video (sorry for the quality):
 2024-09-15.00-19-04.gif (view on web)

**Comment by Ssentiago** [comment]
> 1. I pull all latest files from github respository, as seen above
> 2. Execute "tsc"
> 3. I got 4 files : main.js, main.d.ts, constants.js, constants.d.ts
> 4. And put 6 files into the doc "G:\ObsidianFile\ObsidianPlugin\.obsidian\plugins\mermaid-zoom-drag"&nbsp;
> 
> 
> 
> 5. Load in ob, then I got the error
> 
> 
> 
> 
> 
> ------------------------------
> 
> 
> I don't know how to load the plugin if it has more one file.
> The key point is I don't know how to use "require" in ob js and wether to put the *.d.ts files to release.
> 
> 
> I just want to make a test before releasing,&nbsp; and I had problems about pulling files before for quite a while, finally shooted out.
> So I come to the testing part, and encounter the loading problem above.
> Could you please give me some tips?
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年9月15日(星期天) 凌晨5:31
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Allow other elements, like mehrmaid (Issue #1)
> 
> 
> 
> 
> 
>   
> Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.
>   
> There is no release with this fix yet, please wait for @gitcpy to create one.
>  
> But the fix works, here's a video (sorry for the quality):
>  2024-09-15.00-19-04.gif (view on web)
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Please implement a full-fledged bundler into the project. Webpack, esbuild, rollup, etc. I use rollup locally (I don't push these settings to the repository) and everything works for me. But if you're interested, I could share my settings — then you would just need to install the packages and subsequently run the scripts from package.json.

**Comment by gitcpy** [comment]
I am the amateur, you are the pro.
Please push the settings.
I am just a backend programmer. 
It is lucky to meet you, and I learned much from you by this plugin.

And I will go to learn rollup, then make a test.
Before I make the latest release, you are already a collaborator.
I don't know if you have the right to make a release, if you do, just make it.
Thank you in all!


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月15日(星期天) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Allow other elements, like mehrmaid (Issue #1)





   
 
I pull all latest files from github respository, as seen above
 
 
 
Execute "tsc"
 
 
 
I got 4 files : main.js, main.d.ts, constants.js, constants.d.ts
 
 
 
And put 6 files into the doc "G:\ObsidianFile\ObsidianPlugin.obsidian\plugins\mermaid-zoom-drag" 
 
 
 
Load in ob, then I got the error
 
  
 
I don't know how to load the plugin if it has more one file.
 The key point is I don't know how to use "require" in ob js and wether to put the *.d.ts files to release.
 
I just want to make a test before releasing,&nbsp; and I had problems about pulling files before for quite a while, finally shooted out.
 So I come to the testing part, and encounter the loading problem above.
 Could you please give me some tips?
 
------------------ 原始邮件 ------------------
 发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    @.&gt;;
 发送时间: 2024年9月15日(星期天) 凌晨5:31
 @.&gt;;
 @.@.&gt;;
 主题: Re: [gitcpy/mermaid-zoom-drag] Allow other elements, like mehrmaid (Issue #1)
 
Have you tested this version with mehrmaid? Because unfortunately it does not work for me. Only mermaid diagrams get the buttons but not the mehrmaid ones.
 
There is no release with this fix yet, please wait for @gitcpy to create one.
 
But the fix works, here's a video (sorry for the quality):
 2024-09-15.00-19-04.gif (view on web)
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you were mentioned.Message ID: @.***&gt;
  
Please implement a full-fledged bundler into the project. Webpack, esbuild, rollup, etc. I use rollup locally (I don't push these settings to the repository) and everything works for me. But if you're interested, I could share my settings — then you would just need to install the packages and subsequently run the scripts from package.json.

**Comment by Ssentiago** [comment]
Release is here
